### ISSUE TITLE
Parameterized supertype not supported

### ISSUE THREAD

**Issue by badoualy** [sczerwinski/android-hilt#122]
### Steps

```kotlin
@Bound
class Foo @Inject constructor() : Converter<TypeA, TypeB> { }
```

### Result

```
Caused by: java.lang.ClassCastException: com.squareup.javapoet.ParameterizedTypeName cannot be cast to com.squareup.javapoet.ClassName
	at it.czerwinski.android.hilt.processor.model.BindingBuilder.build(BindingBuilder.kt:59)
	at it.czerwinski.android.hilt.processor.HiltModulesGenerator.createBinding(HiltModulesGenerator.kt:76)
	at it.czerwinski.android.hilt.processor.HiltModulesGenerator.createBindings(HiltModulesGenerator.kt:70)
	at it.czerwinski.android.hilt.processor.HiltModulesGenerator.process(HiltModulesGenerator.kt:51)
```

**Comment by badoualy** [comment]
`MethodSpec.Builder returns` function takes a `TypeName`, so we can update `Binding.supertypeClassName` to be a `TypeName` instead of `ClassName`
